build:
  image: default-jammy
  environment:
    php: 8.2
    variables:
      SKIP_COPY_ASSETS: true
  dependencies:
    before:
      # Install necessary dependencies
      - sudo apt-get update
      - sudo apt-get install -y software-properties-common wget
      # Install PHP 8.2 and necessary modules
      - sudo apt-get install -y php8.2 php8.2-cli php8.2-fpm php8.2-mbstring php8.2-xml php8.2-mysql
      - composer install
  nodes:
    analysis:
      tests:
        # Proper command structure using override
        override:
          - php-scrutinizer-run
    tests:
      tests:
        # Correct syntax for test commands
        override:
          - php-scrutinizer-run

filter:
  paths:
    - "public/*"
  excluded_paths:
    - "vendor/*"

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 4
      switch:
        indent_case: true
    spaces:
      around_operators:
        concatenation: true
