build:
  nodes:
    analysis:
      image: 'php:8.3' # Using Docker Image with PHP 8.3
      environment:
        variables:
          PHP_VERSION: '8.3'
          SKIP_COPY_ASSETS: true
  dependencies:
    before:
      - composer install # Installing dependencies before testing
  tests:
    override:
      - php-scrutinizer-run --enable-security-analysis
      # Run PHP-CS Beautifier and Fixer
      - command: vendor/bin/phpcbf --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Core -s
      # Run PHP-CS
      - command: vendor/bin/phpcs --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Core -s
filter:
  paths:
    - public/* # Routes included in the analysis
    - Modules/*

tools:
  php_analyzer: true
  external_code_coverage:
    enabled: false
    timeout: 600
    filter:
      excluded_paths:
        - 'vendor/*' # Exclude vendor folder from coverage scan

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 4
      switch:
        indent_case: true
    spaces:
      around_operators:
        concatenation: true