checks:
  php: true

tools:
  php_code_sniffer:
    config:
      standard: "PSR12"
  external_code_coverage:
    timeout: 1800
  php_mess_detector: true

build:
  environment:
    php: 8.3
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    tests:
      override:
        - php-scrutinizer-run

filter:
  paths:
    - "public/*"
  excluded_paths:
    - "vendor/*"
