build:
  image: default-bionic
  environment:
    variables:
      PHP_VERSION: 8.3
      SKIP_COPY_ASSETS: true
  dependencies:
    before:
      # Actualizar la lista de paquetes e instalar PHP 8.3
      - sudo add-apt-repository ppa:ondrej/php -y
      - sudo apt-get update
      - sudo apt-get install -y php8.3 php8.3-cli php8.3-fpm php8.3-mbstring php8.3-xml php8.3-mysql
      - composer install
  tests:
    override:
      - php-scrutinizer-run --enable-security-analysis
      # Run PHP-CS Beautifier and Fixer: to format some common non PSR code that can be auto-fixed.
      - command: vendor/bin/phpcbf --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Core -s
      # Run PHP-CS.
      - command: vendor/bin/phpcs --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Core -s
      # Run PHPUnit test.
      # - command: vendor/bin/phpunit --coverage-clover=reports/coverage.xml
filter:
  paths:
    - public/*

tools:
  php_analyzer: true
  external_code_coverage:
    enabled: false
    timeout: 600
    filter:
      excluded_paths:
        - 'vendor/*'

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 4
      switch:
        indent_case: true
    spaces:
      around_operators:
        concatenation: true