# Scrutinizer config for PHP 8.3
checks:
  php: true

tools:
  php_code_sniffer:
    config:
      standard: "PSR12"
  php_mess_detector: true
  php_analyzer: true
  external_code_coverage:
    enabled: false
    timeout: 600
    filter:
      excluded_paths:
        - "vendor/*"

build:
  image: default-jammy
  environment:
    php: 8.3 # Ensure the environment uses PHP 8.3
    variables:
      SKIP_COPY_ASSETS: true
  dependencies:
    before:
      # Install necessary dependencies
      - sudo apt-get update
      - sudo apt-get install -y software-properties-common wget
      # Download and add the PHP repository key
      - wget -q https://packages.sury.org/php/apt.gpg -O- | sudo apt-key add -
      # Add the PHP repository
      - sudo sh -c 'echo "deb https://packages.sury.org/php/ jammy main" > /etc/apt/sources.list.d/php.list'
      - sudo apt-get update
      # Install PHP 8.3 and necessary modules
      - sudo apt-get install -y php8.3 php8.3-cli php8.3-fpm php8.3-mbstring php8.3-xml php8.3-mysql
      - composer install
  nodes:
    analysis:
      tests:
        # Proper command structure using override
        override:
          - php-scrutinizer-run
    tests:
      tests:
        # Correct syntax for test commands
        override:
          - php-scrutinizer-run

filter:
  paths:
    - "public/*"
  excluded_paths:
    - "vendor/*"

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 4
      switch:
        indent_case: true
    spaces:
      around_operators:
        concatenation: true
