# Scrutinizer config for PHP 8.3
checks:
  php: true

tools:
  php_code_sniffer:
    config:
      standard: "PSR12"
  php_mess_detector: true

build:
  image: default-jammy
  environment:
    variables:
      PHP_VERSION: 8.3
      SKIP_COPY_ASSETS: true
  dependencies:
    before:
      # Instalar las dependencias necesarias
      - sudo apt-get update
      - sudo apt-get install -y software-properties-common wget
      # Descargar y agregar la clave del repositorio de PHP
      - wget -q https://packages.sury.org/php/apt.gpg -O- | sudo apt-key add -
      # Agregar el repositorio de PHP
      - sudo sh -c 'echo "deb https://packages.sury.org/php/ jammy main" > /etc/apt/sources.list.d/php.list'
      - sudo apt-get update
      # Instalar PHP 8.3 y los módulos necesarios
      - sudo apt-get install -y php8.3 php8.3-cli php8.3-fpm php8.3-mbstring php8.3-xml php8.3-mysql
      - composer install
  nodes:
    analysis:
      tests:
        # Proper command structure using override
        override:
          - php-scrutinizer-run
    tests:
      tests:
        # Correct syntax for test commands
        override:
          - php-scrutinizer-run

filter:
  paths:
    - "public/*"
  excluded_paths:
    - "vendor/*"

tools:
  php_analyzer: true
  external_code_coverage:
    enabled: false
    timeout: 600
    filter:
      excluded_paths:
        - "vendor/*"

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 4
      switch:
        indent_case: true
    spaces:
      around_operators:
        concatenation: true