# Basic configuration for PHP 8.3
checks:
  php: true

tools:
  php_code_sniffer:
    config:
      standard: "PSR12"
  php_mess_detector: true

build:
  environment:
    php: 8.3
  nodes:
    analysis:
      tests:
        # Remove invalid 'override' and use direct command
        - php-scrutinizer-run
    tests:
      # Remove 'override' and use standard command structure
      commands:
        - php-scrutinizer-run

# Path configuration
filter:
  paths:
    - "public/*"
  excluded_paths:
    - "vendor/*"