# Valid Scrutinizer config for PHP 8.3
checks:
  php: true

tools:
  php_code_sniffer:
    config:
      standard: "PSR12"
  php_mess_detector: true

build:
  environment:
    php: 8.3
  nodes:
    analysis:
      tests:
        # Proper command structure using override
        override:
          - php-scrutinizer-run
    tests:
      tests:
        # Correct syntax for test commands
        override:
          - php-scrutinizer-run

filter:
  paths:
    - "public/*"
  excluded_paths:
    - "vendor/*"